# -*- coding: utf-8 -*-
"""gerador de matriz para memorias.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DBzmTpo1pLDN2bFUJHoK3Ve-ffsxKmnV
"""

from google.colab import files
files.download("saida.csv")

import csv
import random
from google.colab import files

# Nome do arquivo de saída
nome_arquivo = "saida.csv"

# Número de linhas e colunas
linhas = 64
colunas_aleatorias = 8

# Cria o arquivo CSV
with open(nome_arquivo, mode='w', newline='') as arquivo:
    escritor = csv.writer(arquivo)

    # Escreve o cabeçalho (opcional)
    #cabecalho = ["Indice"] + [f"Col{i+1}" for i in range(colunas_aleatorias)]
    #escritor.writerow(cabecalho)

    # Gera as linhas
    for i in range(linhas):
        linha = [i] + [random.randint(0, 1) for _ in range(colunas_aleatorias)]
        escritor.writerow(linha)

print(f"Arquivo '{nome_arquivo}' criado com sucesso!")

# Baixa o arquivo para o seu computador
files.download(nome_arquivo)

